version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: confi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: confi_teste_db
      MYSQL_USER: confi_user
      MYSQL_PASSWORD: confi_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - confi_network

  backend:
    build: ./backend
    container_name: confi_backend
    ports:
      - "8088:8000"
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    environment:
      APP_ENV: development
      APP_DEBUG: "true"
      DB_DRIVER: pdo_mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: confi_teste_db
      DB_USER: confi_user
      DB_PASSWORD: confi_password
      DB_CHARSET: utf8mb4
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - confi_network

  frontend:
    build:
      context: ./frontend
    container_name: confi_frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_API_URL: http://localhost:8088/api
    networks:
      - confi_network

volumes:
  mysql_data:
  backend_vendor:
  frontend_node_modules:

networks:
  confi_network:
    driver: bridge
